{
 "title": "GitHub",
 "time": { "from": "now-1d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "repo",
    "label": "Repositories",
    "query": "label_values(github_exporter_pr_info, repo)"
   }
  ]
 },
 "panels": [
  { "title": "Pull Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Open Pull Requests",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (repo) (github_exporter_pr_info{repo=~\"$repo\",state=\"open\"})",
     "legendFormat": "{{ repo }}"
    }
   ]
  },
  {
   "title": "Open Pull Requests By Team",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (team) (github_exporter_pr_info{repo=~\"$repo\",state=\"open\",team!=\"\"})",
     "legendFormat": "{{ team }}"
    },
    {
     "expr": "sum by (team) (github_exporter_pr_info{repo=~\"$repo\",state=\"open\",team=\"\"})",
     "legendFormat": "(no team)"
    }
   ]
  },
  {
   "title": "Open Pull Requests By Author",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (author) (github_exporter_pr_info{repo=~\"$repo\",state=\"open\"})",
     "legendFormat": "{{ author }}"
    }
   ]
  },
  {
   "title": "Pending Rate",
   "type": "graph",
   "description": "Percentage of pending PRs (WIP/hold/...) in relation to all open PRs in a given repository.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (repo) (github_exporter_pr_info{repo=~\"$repo\",state=\"open\",pending=\"true\"}) / sum by (repo) (github_exporter_pr_info{repo=~\"$repo\",state=\"open\"})",
     "legendFormat": "{{ repo }}"
    }
   ]
  },
  {
   "title": "Open Pull Requests By Size",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 11 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (size) (github_exporter_pr_info{repo=~\"$repo\",state=\"open\",size!=\"\"})",
     "legendFormat": "{{ size }}"
    },
    {
     "expr": "sum by (size) (github_exporter_pr_info{repo=~\"$repo\",state=\"open\",size=\"\"})",
     "legendFormat": "(no size)"
    }
   ]
  },
  {
   "title": "Open Pull Requests by Priority",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 11 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (priority) (github_exporter_pr_info{repo=~\"$repo\",state=\"open\",priority!=\"\"})",
     "legendFormat": "{{ priority }}"
    },
    {
     "expr": "sum by (priority) (github_exporter_pr_info{repo=~\"$repo\",state=\"open\",priority=\"\"})",
     "legendFormat": "(no priority)"
    }
   ]
  },
  { "title": "Issues", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Open Issues",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (repo) (github_exporter_issue_info{repo=~\"$repo\",state=\"open\"})",
     "legendFormat": "{{ repo }}"
    }
   ]
  },
  {
   "title": "Open Issues by Kind",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 22 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (kind) (github_exporter_issue_info{repo=~\"$repo\",state=\"open\",kind!=\"\"})",
     "legendFormat": "{{ kind }}"
    },
    {
     "expr": "sum by (kind) (github_exporter_issue_info{repo=~\"$repo\",state=\"open\",kind=\"\"})",
     "legendFormat": "(no kind)"
    }
   ]
  },
  {
   "title": "Open Issues by Priority",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 22 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (priority) (github_exporter_issue_info{repo=~\"$repo\",state=\"open\",priority!=\"\"})",
     "legendFormat": "{{ priority }}"
    },
    {
     "expr": "sum by (priority) (github_exporter_issue_info{repo=~\"$repo\",state=\"open\",priority=\"\"})",
     "legendFormat": "(no priority)"
    }
   ]
  },
  {
   "title": "Open Issues by Team",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 32 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (team) (github_exporter_issue_info{repo=~\"$repo\",state=\"open\",team!=\"\"})",
     "legendFormat": "{{ team }}"
    },
    {
     "expr": "sum(github_exporter_issue_info{repo=~\"$repo\",state=\"open\",team=\"\"})",
     "legendFormat": "(no team)"
    }
   ]
  },
  {
   "title": "Open Issues by Author",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 32 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (author) (github_exporter_issue_info{repo=~\"$repo\",state=\"open\"})",
     "legendFormat": "{{ author }}"
    }
   ]
  },
  { "title": "Queue Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Pull Requests - Queue Size",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (repo) (github_exporter_pr_queue_size{repo=~\"$repo\"})",
     "legendFormat": "{{ repo }}"
    }
   ]
  },
  {
   "title": "Issues - Queue Size",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (repo) (github_exporter_issue_queue_size{repo=~\"$repo\"})",
     "legendFormat": "{{ repo }}"
    }
   ]
  },
  { "title": "API Client", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "API Request Rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (repo) (rate(github_exporter_api_requests_total{repo=~\"$repo\"}[60m]))",
     "legendFormat": "{{ repo }}"
    }
   ]
  },
  {
   "title": "API Points Remaining",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "github_exporter_api_points_remaining",
     "legendFormat": "points"
    }
   ]
  }
 ]
}