// This file has been generated by hack/generate-client.sh
// Do not edit manually!

package client

import (
	"fmt"
)

const (
	MaxIssuesPerQuery = 100
)

type numberedIssueQuery struct {
	RateLimit  rateLimit
	Repository struct {
		Issue0  *graphqlIssue `graphql:"issue0: issue(number: $number0) @include(if: $has0)"`
		Issue1  *graphqlIssue `graphql:"issue1: issue(number: $number1) @include(if: $has1)"`
		Issue2  *graphqlIssue `graphql:"issue2: issue(number: $number2) @include(if: $has2)"`
		Issue3  *graphqlIssue `graphql:"issue3: issue(number: $number3) @include(if: $has3)"`
		Issue4  *graphqlIssue `graphql:"issue4: issue(number: $number4) @include(if: $has4)"`
		Issue5  *graphqlIssue `graphql:"issue5: issue(number: $number5) @include(if: $has5)"`
		Issue6  *graphqlIssue `graphql:"issue6: issue(number: $number6) @include(if: $has6)"`
		Issue7  *graphqlIssue `graphql:"issue7: issue(number: $number7) @include(if: $has7)"`
		Issue8  *graphqlIssue `graphql:"issue8: issue(number: $number8) @include(if: $has8)"`
		Issue9  *graphqlIssue `graphql:"issue9: issue(number: $number9) @include(if: $has9)"`
		Issue10 *graphqlIssue `graphql:"issue10: issue(number: $number10) @include(if: $has10)"`
		Issue11 *graphqlIssue `graphql:"issue11: issue(number: $number11) @include(if: $has11)"`
		Issue12 *graphqlIssue `graphql:"issue12: issue(number: $number12) @include(if: $has12)"`
		Issue13 *graphqlIssue `graphql:"issue13: issue(number: $number13) @include(if: $has13)"`
		Issue14 *graphqlIssue `graphql:"issue14: issue(number: $number14) @include(if: $has14)"`
		Issue15 *graphqlIssue `graphql:"issue15: issue(number: $number15) @include(if: $has15)"`
		Issue16 *graphqlIssue `graphql:"issue16: issue(number: $number16) @include(if: $has16)"`
		Issue17 *graphqlIssue `graphql:"issue17: issue(number: $number17) @include(if: $has17)"`
		Issue18 *graphqlIssue `graphql:"issue18: issue(number: $number18) @include(if: $has18)"`
		Issue19 *graphqlIssue `graphql:"issue19: issue(number: $number19) @include(if: $has19)"`
		Issue20 *graphqlIssue `graphql:"issue20: issue(number: $number20) @include(if: $has20)"`
		Issue21 *graphqlIssue `graphql:"issue21: issue(number: $number21) @include(if: $has21)"`
		Issue22 *graphqlIssue `graphql:"issue22: issue(number: $number22) @include(if: $has22)"`
		Issue23 *graphqlIssue `graphql:"issue23: issue(number: $number23) @include(if: $has23)"`
		Issue24 *graphqlIssue `graphql:"issue24: issue(number: $number24) @include(if: $has24)"`
		Issue25 *graphqlIssue `graphql:"issue25: issue(number: $number25) @include(if: $has25)"`
		Issue26 *graphqlIssue `graphql:"issue26: issue(number: $number26) @include(if: $has26)"`
		Issue27 *graphqlIssue `graphql:"issue27: issue(number: $number27) @include(if: $has27)"`
		Issue28 *graphqlIssue `graphql:"issue28: issue(number: $number28) @include(if: $has28)"`
		Issue29 *graphqlIssue `graphql:"issue29: issue(number: $number29) @include(if: $has29)"`
		Issue30 *graphqlIssue `graphql:"issue30: issue(number: $number30) @include(if: $has30)"`
		Issue31 *graphqlIssue `graphql:"issue31: issue(number: $number31) @include(if: $has31)"`
		Issue32 *graphqlIssue `graphql:"issue32: issue(number: $number32) @include(if: $has32)"`
		Issue33 *graphqlIssue `graphql:"issue33: issue(number: $number33) @include(if: $has33)"`
		Issue34 *graphqlIssue `graphql:"issue34: issue(number: $number34) @include(if: $has34)"`
		Issue35 *graphqlIssue `graphql:"issue35: issue(number: $number35) @include(if: $has35)"`
		Issue36 *graphqlIssue `graphql:"issue36: issue(number: $number36) @include(if: $has36)"`
		Issue37 *graphqlIssue `graphql:"issue37: issue(number: $number37) @include(if: $has37)"`
		Issue38 *graphqlIssue `graphql:"issue38: issue(number: $number38) @include(if: $has38)"`
		Issue39 *graphqlIssue `graphql:"issue39: issue(number: $number39) @include(if: $has39)"`
		Issue40 *graphqlIssue `graphql:"issue40: issue(number: $number40) @include(if: $has40)"`
		Issue41 *graphqlIssue `graphql:"issue41: issue(number: $number41) @include(if: $has41)"`
		Issue42 *graphqlIssue `graphql:"issue42: issue(number: $number42) @include(if: $has42)"`
		Issue43 *graphqlIssue `graphql:"issue43: issue(number: $number43) @include(if: $has43)"`
		Issue44 *graphqlIssue `graphql:"issue44: issue(number: $number44) @include(if: $has44)"`
		Issue45 *graphqlIssue `graphql:"issue45: issue(number: $number45) @include(if: $has45)"`
		Issue46 *graphqlIssue `graphql:"issue46: issue(number: $number46) @include(if: $has46)"`
		Issue47 *graphqlIssue `graphql:"issue47: issue(number: $number47) @include(if: $has47)"`
		Issue48 *graphqlIssue `graphql:"issue48: issue(number: $number48) @include(if: $has48)"`
		Issue49 *graphqlIssue `graphql:"issue49: issue(number: $number49) @include(if: $has49)"`
		Issue50 *graphqlIssue `graphql:"issue50: issue(number: $number50) @include(if: $has50)"`
		Issue51 *graphqlIssue `graphql:"issue51: issue(number: $number51) @include(if: $has51)"`
		Issue52 *graphqlIssue `graphql:"issue52: issue(number: $number52) @include(if: $has52)"`
		Issue53 *graphqlIssue `graphql:"issue53: issue(number: $number53) @include(if: $has53)"`
		Issue54 *graphqlIssue `graphql:"issue54: issue(number: $number54) @include(if: $has54)"`
		Issue55 *graphqlIssue `graphql:"issue55: issue(number: $number55) @include(if: $has55)"`
		Issue56 *graphqlIssue `graphql:"issue56: issue(number: $number56) @include(if: $has56)"`
		Issue57 *graphqlIssue `graphql:"issue57: issue(number: $number57) @include(if: $has57)"`
		Issue58 *graphqlIssue `graphql:"issue58: issue(number: $number58) @include(if: $has58)"`
		Issue59 *graphqlIssue `graphql:"issue59: issue(number: $number59) @include(if: $has59)"`
		Issue60 *graphqlIssue `graphql:"issue60: issue(number: $number60) @include(if: $has60)"`
		Issue61 *graphqlIssue `graphql:"issue61: issue(number: $number61) @include(if: $has61)"`
		Issue62 *graphqlIssue `graphql:"issue62: issue(number: $number62) @include(if: $has62)"`
		Issue63 *graphqlIssue `graphql:"issue63: issue(number: $number63) @include(if: $has63)"`
		Issue64 *graphqlIssue `graphql:"issue64: issue(number: $number64) @include(if: $has64)"`
		Issue65 *graphqlIssue `graphql:"issue65: issue(number: $number65) @include(if: $has65)"`
		Issue66 *graphqlIssue `graphql:"issue66: issue(number: $number66) @include(if: $has66)"`
		Issue67 *graphqlIssue `graphql:"issue67: issue(number: $number67) @include(if: $has67)"`
		Issue68 *graphqlIssue `graphql:"issue68: issue(number: $number68) @include(if: $has68)"`
		Issue69 *graphqlIssue `graphql:"issue69: issue(number: $number69) @include(if: $has69)"`
		Issue70 *graphqlIssue `graphql:"issue70: issue(number: $number70) @include(if: $has70)"`
		Issue71 *graphqlIssue `graphql:"issue71: issue(number: $number71) @include(if: $has71)"`
		Issue72 *graphqlIssue `graphql:"issue72: issue(number: $number72) @include(if: $has72)"`
		Issue73 *graphqlIssue `graphql:"issue73: issue(number: $number73) @include(if: $has73)"`
		Issue74 *graphqlIssue `graphql:"issue74: issue(number: $number74) @include(if: $has74)"`
		Issue75 *graphqlIssue `graphql:"issue75: issue(number: $number75) @include(if: $has75)"`
		Issue76 *graphqlIssue `graphql:"issue76: issue(number: $number76) @include(if: $has76)"`
		Issue77 *graphqlIssue `graphql:"issue77: issue(number: $number77) @include(if: $has77)"`
		Issue78 *graphqlIssue `graphql:"issue78: issue(number: $number78) @include(if: $has78)"`
		Issue79 *graphqlIssue `graphql:"issue79: issue(number: $number79) @include(if: $has79)"`
		Issue80 *graphqlIssue `graphql:"issue80: issue(number: $number80) @include(if: $has80)"`
		Issue81 *graphqlIssue `graphql:"issue81: issue(number: $number81) @include(if: $has81)"`
		Issue82 *graphqlIssue `graphql:"issue82: issue(number: $number82) @include(if: $has82)"`
		Issue83 *graphqlIssue `graphql:"issue83: issue(number: $number83) @include(if: $has83)"`
		Issue84 *graphqlIssue `graphql:"issue84: issue(number: $number84) @include(if: $has84)"`
		Issue85 *graphqlIssue `graphql:"issue85: issue(number: $number85) @include(if: $has85)"`
		Issue86 *graphqlIssue `graphql:"issue86: issue(number: $number86) @include(if: $has86)"`
		Issue87 *graphqlIssue `graphql:"issue87: issue(number: $number87) @include(if: $has87)"`
		Issue88 *graphqlIssue `graphql:"issue88: issue(number: $number88) @include(if: $has88)"`
		Issue89 *graphqlIssue `graphql:"issue89: issue(number: $number89) @include(if: $has89)"`
		Issue90 *graphqlIssue `graphql:"issue90: issue(number: $number90) @include(if: $has90)"`
		Issue91 *graphqlIssue `graphql:"issue91: issue(number: $number91) @include(if: $has91)"`
		Issue92 *graphqlIssue `graphql:"issue92: issue(number: $number92) @include(if: $has92)"`
		Issue93 *graphqlIssue `graphql:"issue93: issue(number: $number93) @include(if: $has93)"`
		Issue94 *graphqlIssue `graphql:"issue94: issue(number: $number94) @include(if: $has94)"`
		Issue95 *graphqlIssue `graphql:"issue95: issue(number: $number95) @include(if: $has95)"`
		Issue96 *graphqlIssue `graphql:"issue96: issue(number: $number96) @include(if: $has96)"`
		Issue97 *graphqlIssue `graphql:"issue97: issue(number: $number97) @include(if: $has97)"`
		Issue98 *graphqlIssue `graphql:"issue98: issue(number: $number98) @include(if: $has98)"`
		Issue99 *graphqlIssue `graphql:"issue99: issue(number: $number99) @include(if: $has99)"`
	} `graphql:"repository(owner: $owner, name: $name)"`
}

func (r *numberedIssueQuery) GetAll() []graphqlIssue {
	result := []graphqlIssue{}

	for i := 0; i < MaxIssuesPerQuery; i++ {
		if issue := r.Get(i); issue != nil {
			result = append(result, *issue)
		}
	}

	return result
}

func (r *numberedIssueQuery) Get(index int) *graphqlIssue {
	switch index {
	case 0:
		return r.Repository.Issue0
	case 1:
		return r.Repository.Issue1
	case 2:
		return r.Repository.Issue2
	case 3:
		return r.Repository.Issue3
	case 4:
		return r.Repository.Issue4
	case 5:
		return r.Repository.Issue5
	case 6:
		return r.Repository.Issue6
	case 7:
		return r.Repository.Issue7
	case 8:
		return r.Repository.Issue8
	case 9:
		return r.Repository.Issue9
	case 10:
		return r.Repository.Issue10
	case 11:
		return r.Repository.Issue11
	case 12:
		return r.Repository.Issue12
	case 13:
		return r.Repository.Issue13
	case 14:
		return r.Repository.Issue14
	case 15:
		return r.Repository.Issue15
	case 16:
		return r.Repository.Issue16
	case 17:
		return r.Repository.Issue17
	case 18:
		return r.Repository.Issue18
	case 19:
		return r.Repository.Issue19
	case 20:
		return r.Repository.Issue20
	case 21:
		return r.Repository.Issue21
	case 22:
		return r.Repository.Issue22
	case 23:
		return r.Repository.Issue23
	case 24:
		return r.Repository.Issue24
	case 25:
		return r.Repository.Issue25
	case 26:
		return r.Repository.Issue26
	case 27:
		return r.Repository.Issue27
	case 28:
		return r.Repository.Issue28
	case 29:
		return r.Repository.Issue29
	case 30:
		return r.Repository.Issue30
	case 31:
		return r.Repository.Issue31
	case 32:
		return r.Repository.Issue32
	case 33:
		return r.Repository.Issue33
	case 34:
		return r.Repository.Issue34
	case 35:
		return r.Repository.Issue35
	case 36:
		return r.Repository.Issue36
	case 37:
		return r.Repository.Issue37
	case 38:
		return r.Repository.Issue38
	case 39:
		return r.Repository.Issue39
	case 40:
		return r.Repository.Issue40
	case 41:
		return r.Repository.Issue41
	case 42:
		return r.Repository.Issue42
	case 43:
		return r.Repository.Issue43
	case 44:
		return r.Repository.Issue44
	case 45:
		return r.Repository.Issue45
	case 46:
		return r.Repository.Issue46
	case 47:
		return r.Repository.Issue47
	case 48:
		return r.Repository.Issue48
	case 49:
		return r.Repository.Issue49
	case 50:
		return r.Repository.Issue50
	case 51:
		return r.Repository.Issue51
	case 52:
		return r.Repository.Issue52
	case 53:
		return r.Repository.Issue53
	case 54:
		return r.Repository.Issue54
	case 55:
		return r.Repository.Issue55
	case 56:
		return r.Repository.Issue56
	case 57:
		return r.Repository.Issue57
	case 58:
		return r.Repository.Issue58
	case 59:
		return r.Repository.Issue59
	case 60:
		return r.Repository.Issue60
	case 61:
		return r.Repository.Issue61
	case 62:
		return r.Repository.Issue62
	case 63:
		return r.Repository.Issue63
	case 64:
		return r.Repository.Issue64
	case 65:
		return r.Repository.Issue65
	case 66:
		return r.Repository.Issue66
	case 67:
		return r.Repository.Issue67
	case 68:
		return r.Repository.Issue68
	case 69:
		return r.Repository.Issue69
	case 70:
		return r.Repository.Issue70
	case 71:
		return r.Repository.Issue71
	case 72:
		return r.Repository.Issue72
	case 73:
		return r.Repository.Issue73
	case 74:
		return r.Repository.Issue74
	case 75:
		return r.Repository.Issue75
	case 76:
		return r.Repository.Issue76
	case 77:
		return r.Repository.Issue77
	case 78:
		return r.Repository.Issue78
	case 79:
		return r.Repository.Issue79
	case 80:
		return r.Repository.Issue80
	case 81:
		return r.Repository.Issue81
	case 82:
		return r.Repository.Issue82
	case 83:
		return r.Repository.Issue83
	case 84:
		return r.Repository.Issue84
	case 85:
		return r.Repository.Issue85
	case 86:
		return r.Repository.Issue86
	case 87:
		return r.Repository.Issue87
	case 88:
		return r.Repository.Issue88
	case 89:
		return r.Repository.Issue89
	case 90:
		return r.Repository.Issue90
	case 91:
		return r.Repository.Issue91
	case 92:
		return r.Repository.Issue92
	case 93:
		return r.Repository.Issue93
	case 94:
		return r.Repository.Issue94
	case 95:
		return r.Repository.Issue95
	case 96:
		return r.Repository.Issue96
	case 97:
		return r.Repository.Issue97
	case 98:
		return r.Repository.Issue98
	case 99:
		return r.Repository.Issue99
	}

	panic(fmt.Sprintf("Index %d out of range [0,%d] when accessing issue request", index, MaxIssuesPerQuery-1))
}
