// This file has been generated by hack/generate-client.sh
// Do not edit manually!

package client

import (
	"fmt"
)

const (
	MaxMilestonesPerQuery = 100
)

type numberedMilestoneQuery struct {
	RateLimit  rateLimit
	Repository struct {
		Milestone0  *graphqlMilestone `graphql:"milestone0: milestone(number: $number0) @include(if: $has0)"`
		Milestone1  *graphqlMilestone `graphql:"milestone1: milestone(number: $number1) @include(if: $has1)"`
		Milestone2  *graphqlMilestone `graphql:"milestone2: milestone(number: $number2) @include(if: $has2)"`
		Milestone3  *graphqlMilestone `graphql:"milestone3: milestone(number: $number3) @include(if: $has3)"`
		Milestone4  *graphqlMilestone `graphql:"milestone4: milestone(number: $number4) @include(if: $has4)"`
		Milestone5  *graphqlMilestone `graphql:"milestone5: milestone(number: $number5) @include(if: $has5)"`
		Milestone6  *graphqlMilestone `graphql:"milestone6: milestone(number: $number6) @include(if: $has6)"`
		Milestone7  *graphqlMilestone `graphql:"milestone7: milestone(number: $number7) @include(if: $has7)"`
		Milestone8  *graphqlMilestone `graphql:"milestone8: milestone(number: $number8) @include(if: $has8)"`
		Milestone9  *graphqlMilestone `graphql:"milestone9: milestone(number: $number9) @include(if: $has9)"`
		Milestone10 *graphqlMilestone `graphql:"milestone10: milestone(number: $number10) @include(if: $has10)"`
		Milestone11 *graphqlMilestone `graphql:"milestone11: milestone(number: $number11) @include(if: $has11)"`
		Milestone12 *graphqlMilestone `graphql:"milestone12: milestone(number: $number12) @include(if: $has12)"`
		Milestone13 *graphqlMilestone `graphql:"milestone13: milestone(number: $number13) @include(if: $has13)"`
		Milestone14 *graphqlMilestone `graphql:"milestone14: milestone(number: $number14) @include(if: $has14)"`
		Milestone15 *graphqlMilestone `graphql:"milestone15: milestone(number: $number15) @include(if: $has15)"`
		Milestone16 *graphqlMilestone `graphql:"milestone16: milestone(number: $number16) @include(if: $has16)"`
		Milestone17 *graphqlMilestone `graphql:"milestone17: milestone(number: $number17) @include(if: $has17)"`
		Milestone18 *graphqlMilestone `graphql:"milestone18: milestone(number: $number18) @include(if: $has18)"`
		Milestone19 *graphqlMilestone `graphql:"milestone19: milestone(number: $number19) @include(if: $has19)"`
		Milestone20 *graphqlMilestone `graphql:"milestone20: milestone(number: $number20) @include(if: $has20)"`
		Milestone21 *graphqlMilestone `graphql:"milestone21: milestone(number: $number21) @include(if: $has21)"`
		Milestone22 *graphqlMilestone `graphql:"milestone22: milestone(number: $number22) @include(if: $has22)"`
		Milestone23 *graphqlMilestone `graphql:"milestone23: milestone(number: $number23) @include(if: $has23)"`
		Milestone24 *graphqlMilestone `graphql:"milestone24: milestone(number: $number24) @include(if: $has24)"`
		Milestone25 *graphqlMilestone `graphql:"milestone25: milestone(number: $number25) @include(if: $has25)"`
		Milestone26 *graphqlMilestone `graphql:"milestone26: milestone(number: $number26) @include(if: $has26)"`
		Milestone27 *graphqlMilestone `graphql:"milestone27: milestone(number: $number27) @include(if: $has27)"`
		Milestone28 *graphqlMilestone `graphql:"milestone28: milestone(number: $number28) @include(if: $has28)"`
		Milestone29 *graphqlMilestone `graphql:"milestone29: milestone(number: $number29) @include(if: $has29)"`
		Milestone30 *graphqlMilestone `graphql:"milestone30: milestone(number: $number30) @include(if: $has30)"`
		Milestone31 *graphqlMilestone `graphql:"milestone31: milestone(number: $number31) @include(if: $has31)"`
		Milestone32 *graphqlMilestone `graphql:"milestone32: milestone(number: $number32) @include(if: $has32)"`
		Milestone33 *graphqlMilestone `graphql:"milestone33: milestone(number: $number33) @include(if: $has33)"`
		Milestone34 *graphqlMilestone `graphql:"milestone34: milestone(number: $number34) @include(if: $has34)"`
		Milestone35 *graphqlMilestone `graphql:"milestone35: milestone(number: $number35) @include(if: $has35)"`
		Milestone36 *graphqlMilestone `graphql:"milestone36: milestone(number: $number36) @include(if: $has36)"`
		Milestone37 *graphqlMilestone `graphql:"milestone37: milestone(number: $number37) @include(if: $has37)"`
		Milestone38 *graphqlMilestone `graphql:"milestone38: milestone(number: $number38) @include(if: $has38)"`
		Milestone39 *graphqlMilestone `graphql:"milestone39: milestone(number: $number39) @include(if: $has39)"`
		Milestone40 *graphqlMilestone `graphql:"milestone40: milestone(number: $number40) @include(if: $has40)"`
		Milestone41 *graphqlMilestone `graphql:"milestone41: milestone(number: $number41) @include(if: $has41)"`
		Milestone42 *graphqlMilestone `graphql:"milestone42: milestone(number: $number42) @include(if: $has42)"`
		Milestone43 *graphqlMilestone `graphql:"milestone43: milestone(number: $number43) @include(if: $has43)"`
		Milestone44 *graphqlMilestone `graphql:"milestone44: milestone(number: $number44) @include(if: $has44)"`
		Milestone45 *graphqlMilestone `graphql:"milestone45: milestone(number: $number45) @include(if: $has45)"`
		Milestone46 *graphqlMilestone `graphql:"milestone46: milestone(number: $number46) @include(if: $has46)"`
		Milestone47 *graphqlMilestone `graphql:"milestone47: milestone(number: $number47) @include(if: $has47)"`
		Milestone48 *graphqlMilestone `graphql:"milestone48: milestone(number: $number48) @include(if: $has48)"`
		Milestone49 *graphqlMilestone `graphql:"milestone49: milestone(number: $number49) @include(if: $has49)"`
		Milestone50 *graphqlMilestone `graphql:"milestone50: milestone(number: $number50) @include(if: $has50)"`
		Milestone51 *graphqlMilestone `graphql:"milestone51: milestone(number: $number51) @include(if: $has51)"`
		Milestone52 *graphqlMilestone `graphql:"milestone52: milestone(number: $number52) @include(if: $has52)"`
		Milestone53 *graphqlMilestone `graphql:"milestone53: milestone(number: $number53) @include(if: $has53)"`
		Milestone54 *graphqlMilestone `graphql:"milestone54: milestone(number: $number54) @include(if: $has54)"`
		Milestone55 *graphqlMilestone `graphql:"milestone55: milestone(number: $number55) @include(if: $has55)"`
		Milestone56 *graphqlMilestone `graphql:"milestone56: milestone(number: $number56) @include(if: $has56)"`
		Milestone57 *graphqlMilestone `graphql:"milestone57: milestone(number: $number57) @include(if: $has57)"`
		Milestone58 *graphqlMilestone `graphql:"milestone58: milestone(number: $number58) @include(if: $has58)"`
		Milestone59 *graphqlMilestone `graphql:"milestone59: milestone(number: $number59) @include(if: $has59)"`
		Milestone60 *graphqlMilestone `graphql:"milestone60: milestone(number: $number60) @include(if: $has60)"`
		Milestone61 *graphqlMilestone `graphql:"milestone61: milestone(number: $number61) @include(if: $has61)"`
		Milestone62 *graphqlMilestone `graphql:"milestone62: milestone(number: $number62) @include(if: $has62)"`
		Milestone63 *graphqlMilestone `graphql:"milestone63: milestone(number: $number63) @include(if: $has63)"`
		Milestone64 *graphqlMilestone `graphql:"milestone64: milestone(number: $number64) @include(if: $has64)"`
		Milestone65 *graphqlMilestone `graphql:"milestone65: milestone(number: $number65) @include(if: $has65)"`
		Milestone66 *graphqlMilestone `graphql:"milestone66: milestone(number: $number66) @include(if: $has66)"`
		Milestone67 *graphqlMilestone `graphql:"milestone67: milestone(number: $number67) @include(if: $has67)"`
		Milestone68 *graphqlMilestone `graphql:"milestone68: milestone(number: $number68) @include(if: $has68)"`
		Milestone69 *graphqlMilestone `graphql:"milestone69: milestone(number: $number69) @include(if: $has69)"`
		Milestone70 *graphqlMilestone `graphql:"milestone70: milestone(number: $number70) @include(if: $has70)"`
		Milestone71 *graphqlMilestone `graphql:"milestone71: milestone(number: $number71) @include(if: $has71)"`
		Milestone72 *graphqlMilestone `graphql:"milestone72: milestone(number: $number72) @include(if: $has72)"`
		Milestone73 *graphqlMilestone `graphql:"milestone73: milestone(number: $number73) @include(if: $has73)"`
		Milestone74 *graphqlMilestone `graphql:"milestone74: milestone(number: $number74) @include(if: $has74)"`
		Milestone75 *graphqlMilestone `graphql:"milestone75: milestone(number: $number75) @include(if: $has75)"`
		Milestone76 *graphqlMilestone `graphql:"milestone76: milestone(number: $number76) @include(if: $has76)"`
		Milestone77 *graphqlMilestone `graphql:"milestone77: milestone(number: $number77) @include(if: $has77)"`
		Milestone78 *graphqlMilestone `graphql:"milestone78: milestone(number: $number78) @include(if: $has78)"`
		Milestone79 *graphqlMilestone `graphql:"milestone79: milestone(number: $number79) @include(if: $has79)"`
		Milestone80 *graphqlMilestone `graphql:"milestone80: milestone(number: $number80) @include(if: $has80)"`
		Milestone81 *graphqlMilestone `graphql:"milestone81: milestone(number: $number81) @include(if: $has81)"`
		Milestone82 *graphqlMilestone `graphql:"milestone82: milestone(number: $number82) @include(if: $has82)"`
		Milestone83 *graphqlMilestone `graphql:"milestone83: milestone(number: $number83) @include(if: $has83)"`
		Milestone84 *graphqlMilestone `graphql:"milestone84: milestone(number: $number84) @include(if: $has84)"`
		Milestone85 *graphqlMilestone `graphql:"milestone85: milestone(number: $number85) @include(if: $has85)"`
		Milestone86 *graphqlMilestone `graphql:"milestone86: milestone(number: $number86) @include(if: $has86)"`
		Milestone87 *graphqlMilestone `graphql:"milestone87: milestone(number: $number87) @include(if: $has87)"`
		Milestone88 *graphqlMilestone `graphql:"milestone88: milestone(number: $number88) @include(if: $has88)"`
		Milestone89 *graphqlMilestone `graphql:"milestone89: milestone(number: $number89) @include(if: $has89)"`
		Milestone90 *graphqlMilestone `graphql:"milestone90: milestone(number: $number90) @include(if: $has90)"`
		Milestone91 *graphqlMilestone `graphql:"milestone91: milestone(number: $number91) @include(if: $has91)"`
		Milestone92 *graphqlMilestone `graphql:"milestone92: milestone(number: $number92) @include(if: $has92)"`
		Milestone93 *graphqlMilestone `graphql:"milestone93: milestone(number: $number93) @include(if: $has93)"`
		Milestone94 *graphqlMilestone `graphql:"milestone94: milestone(number: $number94) @include(if: $has94)"`
		Milestone95 *graphqlMilestone `graphql:"milestone95: milestone(number: $number95) @include(if: $has95)"`
		Milestone96 *graphqlMilestone `graphql:"milestone96: milestone(number: $number96) @include(if: $has96)"`
		Milestone97 *graphqlMilestone `graphql:"milestone97: milestone(number: $number97) @include(if: $has97)"`
		Milestone98 *graphqlMilestone `graphql:"milestone98: milestone(number: $number98) @include(if: $has98)"`
		Milestone99 *graphqlMilestone `graphql:"milestone99: milestone(number: $number99) @include(if: $has99)"`
	} `graphql:"repository(owner: $owner, name: $name)"`
}

func (r *numberedMilestoneQuery) GetAll() []graphqlMilestone {
	result := []graphqlMilestone{}

	for i := 0; i < MaxMilestonesPerQuery; i++ {
		if milestone := r.Get(i); milestone != nil {
			result = append(result, *milestone)
		}
	}

	return result
}

func (r *numberedMilestoneQuery) Get(index int) *graphqlMilestone {
	switch index {
	case 0:
		return r.Repository.Milestone0
	case 1:
		return r.Repository.Milestone1
	case 2:
		return r.Repository.Milestone2
	case 3:
		return r.Repository.Milestone3
	case 4:
		return r.Repository.Milestone4
	case 5:
		return r.Repository.Milestone5
	case 6:
		return r.Repository.Milestone6
	case 7:
		return r.Repository.Milestone7
	case 8:
		return r.Repository.Milestone8
	case 9:
		return r.Repository.Milestone9
	case 10:
		return r.Repository.Milestone10
	case 11:
		return r.Repository.Milestone11
	case 12:
		return r.Repository.Milestone12
	case 13:
		return r.Repository.Milestone13
	case 14:
		return r.Repository.Milestone14
	case 15:
		return r.Repository.Milestone15
	case 16:
		return r.Repository.Milestone16
	case 17:
		return r.Repository.Milestone17
	case 18:
		return r.Repository.Milestone18
	case 19:
		return r.Repository.Milestone19
	case 20:
		return r.Repository.Milestone20
	case 21:
		return r.Repository.Milestone21
	case 22:
		return r.Repository.Milestone22
	case 23:
		return r.Repository.Milestone23
	case 24:
		return r.Repository.Milestone24
	case 25:
		return r.Repository.Milestone25
	case 26:
		return r.Repository.Milestone26
	case 27:
		return r.Repository.Milestone27
	case 28:
		return r.Repository.Milestone28
	case 29:
		return r.Repository.Milestone29
	case 30:
		return r.Repository.Milestone30
	case 31:
		return r.Repository.Milestone31
	case 32:
		return r.Repository.Milestone32
	case 33:
		return r.Repository.Milestone33
	case 34:
		return r.Repository.Milestone34
	case 35:
		return r.Repository.Milestone35
	case 36:
		return r.Repository.Milestone36
	case 37:
		return r.Repository.Milestone37
	case 38:
		return r.Repository.Milestone38
	case 39:
		return r.Repository.Milestone39
	case 40:
		return r.Repository.Milestone40
	case 41:
		return r.Repository.Milestone41
	case 42:
		return r.Repository.Milestone42
	case 43:
		return r.Repository.Milestone43
	case 44:
		return r.Repository.Milestone44
	case 45:
		return r.Repository.Milestone45
	case 46:
		return r.Repository.Milestone46
	case 47:
		return r.Repository.Milestone47
	case 48:
		return r.Repository.Milestone48
	case 49:
		return r.Repository.Milestone49
	case 50:
		return r.Repository.Milestone50
	case 51:
		return r.Repository.Milestone51
	case 52:
		return r.Repository.Milestone52
	case 53:
		return r.Repository.Milestone53
	case 54:
		return r.Repository.Milestone54
	case 55:
		return r.Repository.Milestone55
	case 56:
		return r.Repository.Milestone56
	case 57:
		return r.Repository.Milestone57
	case 58:
		return r.Repository.Milestone58
	case 59:
		return r.Repository.Milestone59
	case 60:
		return r.Repository.Milestone60
	case 61:
		return r.Repository.Milestone61
	case 62:
		return r.Repository.Milestone62
	case 63:
		return r.Repository.Milestone63
	case 64:
		return r.Repository.Milestone64
	case 65:
		return r.Repository.Milestone65
	case 66:
		return r.Repository.Milestone66
	case 67:
		return r.Repository.Milestone67
	case 68:
		return r.Repository.Milestone68
	case 69:
		return r.Repository.Milestone69
	case 70:
		return r.Repository.Milestone70
	case 71:
		return r.Repository.Milestone71
	case 72:
		return r.Repository.Milestone72
	case 73:
		return r.Repository.Milestone73
	case 74:
		return r.Repository.Milestone74
	case 75:
		return r.Repository.Milestone75
	case 76:
		return r.Repository.Milestone76
	case 77:
		return r.Repository.Milestone77
	case 78:
		return r.Repository.Milestone78
	case 79:
		return r.Repository.Milestone79
	case 80:
		return r.Repository.Milestone80
	case 81:
		return r.Repository.Milestone81
	case 82:
		return r.Repository.Milestone82
	case 83:
		return r.Repository.Milestone83
	case 84:
		return r.Repository.Milestone84
	case 85:
		return r.Repository.Milestone85
	case 86:
		return r.Repository.Milestone86
	case 87:
		return r.Repository.Milestone87
	case 88:
		return r.Repository.Milestone88
	case 89:
		return r.Repository.Milestone89
	case 90:
		return r.Repository.Milestone90
	case 91:
		return r.Repository.Milestone91
	case 92:
		return r.Repository.Milestone92
	case 93:
		return r.Repository.Milestone93
	case 94:
		return r.Repository.Milestone94
	case 95:
		return r.Repository.Milestone95
	case 96:
		return r.Repository.Milestone96
	case 97:
		return r.Repository.Milestone97
	case 98:
		return r.Repository.Milestone98
	case 99:
		return r.Repository.Milestone99
	}

	panic(fmt.Sprintf("Index %d out of range [0,%d] when accessing milestone request", index, MaxMilestonesPerQuery-1))
}
