// This file has been generated by hack/generate-client.sh
// Do not edit manually!

package client

import (
	"fmt"
)

const (
	MaxPullRequestsPerQuery = 100
)

type numberedPullRequestQuery struct {
	RateLimit  rateLimit
	Repository struct {
		Pr0  *graphqlPullRequest `graphql:"pr0: pullRequest(number: $number0) @include(if: $has0)"`
		Pr1  *graphqlPullRequest `graphql:"pr1: pullRequest(number: $number1) @include(if: $has1)"`
		Pr2  *graphqlPullRequest `graphql:"pr2: pullRequest(number: $number2) @include(if: $has2)"`
		Pr3  *graphqlPullRequest `graphql:"pr3: pullRequest(number: $number3) @include(if: $has3)"`
		Pr4  *graphqlPullRequest `graphql:"pr4: pullRequest(number: $number4) @include(if: $has4)"`
		Pr5  *graphqlPullRequest `graphql:"pr5: pullRequest(number: $number5) @include(if: $has5)"`
		Pr6  *graphqlPullRequest `graphql:"pr6: pullRequest(number: $number6) @include(if: $has6)"`
		Pr7  *graphqlPullRequest `graphql:"pr7: pullRequest(number: $number7) @include(if: $has7)"`
		Pr8  *graphqlPullRequest `graphql:"pr8: pullRequest(number: $number8) @include(if: $has8)"`
		Pr9  *graphqlPullRequest `graphql:"pr9: pullRequest(number: $number9) @include(if: $has9)"`
		Pr10 *graphqlPullRequest `graphql:"pr10: pullRequest(number: $number10) @include(if: $has10)"`
		Pr11 *graphqlPullRequest `graphql:"pr11: pullRequest(number: $number11) @include(if: $has11)"`
		Pr12 *graphqlPullRequest `graphql:"pr12: pullRequest(number: $number12) @include(if: $has12)"`
		Pr13 *graphqlPullRequest `graphql:"pr13: pullRequest(number: $number13) @include(if: $has13)"`
		Pr14 *graphqlPullRequest `graphql:"pr14: pullRequest(number: $number14) @include(if: $has14)"`
		Pr15 *graphqlPullRequest `graphql:"pr15: pullRequest(number: $number15) @include(if: $has15)"`
		Pr16 *graphqlPullRequest `graphql:"pr16: pullRequest(number: $number16) @include(if: $has16)"`
		Pr17 *graphqlPullRequest `graphql:"pr17: pullRequest(number: $number17) @include(if: $has17)"`
		Pr18 *graphqlPullRequest `graphql:"pr18: pullRequest(number: $number18) @include(if: $has18)"`
		Pr19 *graphqlPullRequest `graphql:"pr19: pullRequest(number: $number19) @include(if: $has19)"`
		Pr20 *graphqlPullRequest `graphql:"pr20: pullRequest(number: $number20) @include(if: $has20)"`
		Pr21 *graphqlPullRequest `graphql:"pr21: pullRequest(number: $number21) @include(if: $has21)"`
		Pr22 *graphqlPullRequest `graphql:"pr22: pullRequest(number: $number22) @include(if: $has22)"`
		Pr23 *graphqlPullRequest `graphql:"pr23: pullRequest(number: $number23) @include(if: $has23)"`
		Pr24 *graphqlPullRequest `graphql:"pr24: pullRequest(number: $number24) @include(if: $has24)"`
		Pr25 *graphqlPullRequest `graphql:"pr25: pullRequest(number: $number25) @include(if: $has25)"`
		Pr26 *graphqlPullRequest `graphql:"pr26: pullRequest(number: $number26) @include(if: $has26)"`
		Pr27 *graphqlPullRequest `graphql:"pr27: pullRequest(number: $number27) @include(if: $has27)"`
		Pr28 *graphqlPullRequest `graphql:"pr28: pullRequest(number: $number28) @include(if: $has28)"`
		Pr29 *graphqlPullRequest `graphql:"pr29: pullRequest(number: $number29) @include(if: $has29)"`
		Pr30 *graphqlPullRequest `graphql:"pr30: pullRequest(number: $number30) @include(if: $has30)"`
		Pr31 *graphqlPullRequest `graphql:"pr31: pullRequest(number: $number31) @include(if: $has31)"`
		Pr32 *graphqlPullRequest `graphql:"pr32: pullRequest(number: $number32) @include(if: $has32)"`
		Pr33 *graphqlPullRequest `graphql:"pr33: pullRequest(number: $number33) @include(if: $has33)"`
		Pr34 *graphqlPullRequest `graphql:"pr34: pullRequest(number: $number34) @include(if: $has34)"`
		Pr35 *graphqlPullRequest `graphql:"pr35: pullRequest(number: $number35) @include(if: $has35)"`
		Pr36 *graphqlPullRequest `graphql:"pr36: pullRequest(number: $number36) @include(if: $has36)"`
		Pr37 *graphqlPullRequest `graphql:"pr37: pullRequest(number: $number37) @include(if: $has37)"`
		Pr38 *graphqlPullRequest `graphql:"pr38: pullRequest(number: $number38) @include(if: $has38)"`
		Pr39 *graphqlPullRequest `graphql:"pr39: pullRequest(number: $number39) @include(if: $has39)"`
		Pr40 *graphqlPullRequest `graphql:"pr40: pullRequest(number: $number40) @include(if: $has40)"`
		Pr41 *graphqlPullRequest `graphql:"pr41: pullRequest(number: $number41) @include(if: $has41)"`
		Pr42 *graphqlPullRequest `graphql:"pr42: pullRequest(number: $number42) @include(if: $has42)"`
		Pr43 *graphqlPullRequest `graphql:"pr43: pullRequest(number: $number43) @include(if: $has43)"`
		Pr44 *graphqlPullRequest `graphql:"pr44: pullRequest(number: $number44) @include(if: $has44)"`
		Pr45 *graphqlPullRequest `graphql:"pr45: pullRequest(number: $number45) @include(if: $has45)"`
		Pr46 *graphqlPullRequest `graphql:"pr46: pullRequest(number: $number46) @include(if: $has46)"`
		Pr47 *graphqlPullRequest `graphql:"pr47: pullRequest(number: $number47) @include(if: $has47)"`
		Pr48 *graphqlPullRequest `graphql:"pr48: pullRequest(number: $number48) @include(if: $has48)"`
		Pr49 *graphqlPullRequest `graphql:"pr49: pullRequest(number: $number49) @include(if: $has49)"`
		Pr50 *graphqlPullRequest `graphql:"pr50: pullRequest(number: $number50) @include(if: $has50)"`
		Pr51 *graphqlPullRequest `graphql:"pr51: pullRequest(number: $number51) @include(if: $has51)"`
		Pr52 *graphqlPullRequest `graphql:"pr52: pullRequest(number: $number52) @include(if: $has52)"`
		Pr53 *graphqlPullRequest `graphql:"pr53: pullRequest(number: $number53) @include(if: $has53)"`
		Pr54 *graphqlPullRequest `graphql:"pr54: pullRequest(number: $number54) @include(if: $has54)"`
		Pr55 *graphqlPullRequest `graphql:"pr55: pullRequest(number: $number55) @include(if: $has55)"`
		Pr56 *graphqlPullRequest `graphql:"pr56: pullRequest(number: $number56) @include(if: $has56)"`
		Pr57 *graphqlPullRequest `graphql:"pr57: pullRequest(number: $number57) @include(if: $has57)"`
		Pr58 *graphqlPullRequest `graphql:"pr58: pullRequest(number: $number58) @include(if: $has58)"`
		Pr59 *graphqlPullRequest `graphql:"pr59: pullRequest(number: $number59) @include(if: $has59)"`
		Pr60 *graphqlPullRequest `graphql:"pr60: pullRequest(number: $number60) @include(if: $has60)"`
		Pr61 *graphqlPullRequest `graphql:"pr61: pullRequest(number: $number61) @include(if: $has61)"`
		Pr62 *graphqlPullRequest `graphql:"pr62: pullRequest(number: $number62) @include(if: $has62)"`
		Pr63 *graphqlPullRequest `graphql:"pr63: pullRequest(number: $number63) @include(if: $has63)"`
		Pr64 *graphqlPullRequest `graphql:"pr64: pullRequest(number: $number64) @include(if: $has64)"`
		Pr65 *graphqlPullRequest `graphql:"pr65: pullRequest(number: $number65) @include(if: $has65)"`
		Pr66 *graphqlPullRequest `graphql:"pr66: pullRequest(number: $number66) @include(if: $has66)"`
		Pr67 *graphqlPullRequest `graphql:"pr67: pullRequest(number: $number67) @include(if: $has67)"`
		Pr68 *graphqlPullRequest `graphql:"pr68: pullRequest(number: $number68) @include(if: $has68)"`
		Pr69 *graphqlPullRequest `graphql:"pr69: pullRequest(number: $number69) @include(if: $has69)"`
		Pr70 *graphqlPullRequest `graphql:"pr70: pullRequest(number: $number70) @include(if: $has70)"`
		Pr71 *graphqlPullRequest `graphql:"pr71: pullRequest(number: $number71) @include(if: $has71)"`
		Pr72 *graphqlPullRequest `graphql:"pr72: pullRequest(number: $number72) @include(if: $has72)"`
		Pr73 *graphqlPullRequest `graphql:"pr73: pullRequest(number: $number73) @include(if: $has73)"`
		Pr74 *graphqlPullRequest `graphql:"pr74: pullRequest(number: $number74) @include(if: $has74)"`
		Pr75 *graphqlPullRequest `graphql:"pr75: pullRequest(number: $number75) @include(if: $has75)"`
		Pr76 *graphqlPullRequest `graphql:"pr76: pullRequest(number: $number76) @include(if: $has76)"`
		Pr77 *graphqlPullRequest `graphql:"pr77: pullRequest(number: $number77) @include(if: $has77)"`
		Pr78 *graphqlPullRequest `graphql:"pr78: pullRequest(number: $number78) @include(if: $has78)"`
		Pr79 *graphqlPullRequest `graphql:"pr79: pullRequest(number: $number79) @include(if: $has79)"`
		Pr80 *graphqlPullRequest `graphql:"pr80: pullRequest(number: $number80) @include(if: $has80)"`
		Pr81 *graphqlPullRequest `graphql:"pr81: pullRequest(number: $number81) @include(if: $has81)"`
		Pr82 *graphqlPullRequest `graphql:"pr82: pullRequest(number: $number82) @include(if: $has82)"`
		Pr83 *graphqlPullRequest `graphql:"pr83: pullRequest(number: $number83) @include(if: $has83)"`
		Pr84 *graphqlPullRequest `graphql:"pr84: pullRequest(number: $number84) @include(if: $has84)"`
		Pr85 *graphqlPullRequest `graphql:"pr85: pullRequest(number: $number85) @include(if: $has85)"`
		Pr86 *graphqlPullRequest `graphql:"pr86: pullRequest(number: $number86) @include(if: $has86)"`
		Pr87 *graphqlPullRequest `graphql:"pr87: pullRequest(number: $number87) @include(if: $has87)"`
		Pr88 *graphqlPullRequest `graphql:"pr88: pullRequest(number: $number88) @include(if: $has88)"`
		Pr89 *graphqlPullRequest `graphql:"pr89: pullRequest(number: $number89) @include(if: $has89)"`
		Pr90 *graphqlPullRequest `graphql:"pr90: pullRequest(number: $number90) @include(if: $has90)"`
		Pr91 *graphqlPullRequest `graphql:"pr91: pullRequest(number: $number91) @include(if: $has91)"`
		Pr92 *graphqlPullRequest `graphql:"pr92: pullRequest(number: $number92) @include(if: $has92)"`
		Pr93 *graphqlPullRequest `graphql:"pr93: pullRequest(number: $number93) @include(if: $has93)"`
		Pr94 *graphqlPullRequest `graphql:"pr94: pullRequest(number: $number94) @include(if: $has94)"`
		Pr95 *graphqlPullRequest `graphql:"pr95: pullRequest(number: $number95) @include(if: $has95)"`
		Pr96 *graphqlPullRequest `graphql:"pr96: pullRequest(number: $number96) @include(if: $has96)"`
		Pr97 *graphqlPullRequest `graphql:"pr97: pullRequest(number: $number97) @include(if: $has97)"`
		Pr98 *graphqlPullRequest `graphql:"pr98: pullRequest(number: $number98) @include(if: $has98)"`
		Pr99 *graphqlPullRequest `graphql:"pr99: pullRequest(number: $number99) @include(if: $has99)"`
	} `graphql:"repository(owner: $owner, name: $name)"`
}

func (r *numberedPullRequestQuery) GetAll() []graphqlPullRequest {
	result := []graphqlPullRequest{}

	for i := 0; i < MaxPullRequestsPerQuery; i++ {
		if pr := r.Get(i); pr != nil {
			result = append(result, *pr)
		}
	}

	return result
}

func (r *numberedPullRequestQuery) Get(index int) *graphqlPullRequest {
	switch index {
	case 0:
		return r.Repository.Pr0
	case 1:
		return r.Repository.Pr1
	case 2:
		return r.Repository.Pr2
	case 3:
		return r.Repository.Pr3
	case 4:
		return r.Repository.Pr4
	case 5:
		return r.Repository.Pr5
	case 6:
		return r.Repository.Pr6
	case 7:
		return r.Repository.Pr7
	case 8:
		return r.Repository.Pr8
	case 9:
		return r.Repository.Pr9
	case 10:
		return r.Repository.Pr10
	case 11:
		return r.Repository.Pr11
	case 12:
		return r.Repository.Pr12
	case 13:
		return r.Repository.Pr13
	case 14:
		return r.Repository.Pr14
	case 15:
		return r.Repository.Pr15
	case 16:
		return r.Repository.Pr16
	case 17:
		return r.Repository.Pr17
	case 18:
		return r.Repository.Pr18
	case 19:
		return r.Repository.Pr19
	case 20:
		return r.Repository.Pr20
	case 21:
		return r.Repository.Pr21
	case 22:
		return r.Repository.Pr22
	case 23:
		return r.Repository.Pr23
	case 24:
		return r.Repository.Pr24
	case 25:
		return r.Repository.Pr25
	case 26:
		return r.Repository.Pr26
	case 27:
		return r.Repository.Pr27
	case 28:
		return r.Repository.Pr28
	case 29:
		return r.Repository.Pr29
	case 30:
		return r.Repository.Pr30
	case 31:
		return r.Repository.Pr31
	case 32:
		return r.Repository.Pr32
	case 33:
		return r.Repository.Pr33
	case 34:
		return r.Repository.Pr34
	case 35:
		return r.Repository.Pr35
	case 36:
		return r.Repository.Pr36
	case 37:
		return r.Repository.Pr37
	case 38:
		return r.Repository.Pr38
	case 39:
		return r.Repository.Pr39
	case 40:
		return r.Repository.Pr40
	case 41:
		return r.Repository.Pr41
	case 42:
		return r.Repository.Pr42
	case 43:
		return r.Repository.Pr43
	case 44:
		return r.Repository.Pr44
	case 45:
		return r.Repository.Pr45
	case 46:
		return r.Repository.Pr46
	case 47:
		return r.Repository.Pr47
	case 48:
		return r.Repository.Pr48
	case 49:
		return r.Repository.Pr49
	case 50:
		return r.Repository.Pr50
	case 51:
		return r.Repository.Pr51
	case 52:
		return r.Repository.Pr52
	case 53:
		return r.Repository.Pr53
	case 54:
		return r.Repository.Pr54
	case 55:
		return r.Repository.Pr55
	case 56:
		return r.Repository.Pr56
	case 57:
		return r.Repository.Pr57
	case 58:
		return r.Repository.Pr58
	case 59:
		return r.Repository.Pr59
	case 60:
		return r.Repository.Pr60
	case 61:
		return r.Repository.Pr61
	case 62:
		return r.Repository.Pr62
	case 63:
		return r.Repository.Pr63
	case 64:
		return r.Repository.Pr64
	case 65:
		return r.Repository.Pr65
	case 66:
		return r.Repository.Pr66
	case 67:
		return r.Repository.Pr67
	case 68:
		return r.Repository.Pr68
	case 69:
		return r.Repository.Pr69
	case 70:
		return r.Repository.Pr70
	case 71:
		return r.Repository.Pr71
	case 72:
		return r.Repository.Pr72
	case 73:
		return r.Repository.Pr73
	case 74:
		return r.Repository.Pr74
	case 75:
		return r.Repository.Pr75
	case 76:
		return r.Repository.Pr76
	case 77:
		return r.Repository.Pr77
	case 78:
		return r.Repository.Pr78
	case 79:
		return r.Repository.Pr79
	case 80:
		return r.Repository.Pr80
	case 81:
		return r.Repository.Pr81
	case 82:
		return r.Repository.Pr82
	case 83:
		return r.Repository.Pr83
	case 84:
		return r.Repository.Pr84
	case 85:
		return r.Repository.Pr85
	case 86:
		return r.Repository.Pr86
	case 87:
		return r.Repository.Pr87
	case 88:
		return r.Repository.Pr88
	case 89:
		return r.Repository.Pr89
	case 90:
		return r.Repository.Pr90
	case 91:
		return r.Repository.Pr91
	case 92:
		return r.Repository.Pr92
	case 93:
		return r.Repository.Pr93
	case 94:
		return r.Repository.Pr94
	case 95:
		return r.Repository.Pr95
	case 96:
		return r.Repository.Pr96
	case 97:
		return r.Repository.Pr97
	case 98:
		return r.Repository.Pr98
	case 99:
		return r.Repository.Pr99
	}

	panic(fmt.Sprintf("Index %d out of range [0,%d] when accessing PR request", index, MaxPullRequestsPerQuery-1))
}
